version: 0.0.1

# Change default server ports
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
health:
  delayedShutdownHandlerEnabled: true
  shutdownWaitPeriod: 5s
  healthCheckUrlPaths: ["/healthcheck"]
  healthChecks:
    - name: cassandra
      critical: true
      schedule:
        checkInterval: 2500ms
        downtimeInterval: 10s
        failureAttempts: 2
        successAttempts: 1